feat: Add component benchmark test for CasbinEvaluator.
casbin-net/casbin-aspnetcore pull request #47
Opened 2022-08-02 04:11 UTC by AsakusaRinne

This PR adds benchmark test for component. It adds some test for ```CasbinEvaluator```.

2022-08-17 18:55 UTC, sagilio reviewed
Plz upload the test result to the Actions artifacts.

2022-08-24 09:23 UTC, hsluoyz requested changes

2022-08-24 09:23 UTC, hsluoyz commented on test/Casbin.AspNetCore.Performance/Casbin.AspNetCore.Performance.csproj
> +    <TargetFrameworks>net6;net5;netcoreapp3.1</TargetFrameworks>
11 min is too long

![image](https://user-images.githubusercontent.com/3787410/186382058-c27590b5-5417-4304-9e14-335d3b4d976f.png)

2022-08-25 14:20 UTC, hsluoyz approved these changes

2022-08-25 14:20 UTC, merged